
import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Model = forwardRef(function Model(props, ref) {
  const { nodes, materials } = useGLTF('/assets/heroSatellite.glb')
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube050.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube051.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube052.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube060.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube062.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube063.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube064.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube065.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube066.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube067.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube068.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube070.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube071.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube072.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube073.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube074.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube075.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube076.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube077.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube078.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube079.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube080.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube082.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube084.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube085.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube086.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube087.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube088.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube089.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube090.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube091.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube092.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube093.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube094.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube095.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube096.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube097.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube098.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube099.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube100.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube101.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube102.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube103.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube104.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube105.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube106.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube107.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube108.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube109.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube110.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube111.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube112.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube113.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube114.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube115.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube116.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube117.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube118.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube119.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube120.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube121.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube122.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube123.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube124.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube125.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube126.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube127.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube128.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube129.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube130.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube131.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube132.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube133.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube134.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube135.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube136.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube137.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube138.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube139.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube140.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube141.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube142.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube143.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube144.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube145.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube146.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube147.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube148.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube149.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube150.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube151.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube152.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube153.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube154.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube155.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube156.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube157.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube158.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube159.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube160.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube161.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube162.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube163.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube164.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube165.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube166.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube167.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube168.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube169.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube170.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube171.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube172.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube173.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube174.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube175.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube176.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube177.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube178.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube179.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube180.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube181.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube182.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube183.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube184.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube185.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube186.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube187.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube188.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube189.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube190.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube191.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube192.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube193.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube194.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube195.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube196.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube197.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube198.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube199.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube200.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube201.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube202.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube203.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube204.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube205.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube206.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube207.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube208.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube209.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube210.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube211.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube212.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube213.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube214.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube215.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube216.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube217.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube218.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube219.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube220.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube221.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube222.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube223.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube224.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube225.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube226.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube227.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube228.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube229.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube230.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube231.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube232.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube233.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube234.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube235.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube236.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube237.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube238.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube239.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube240.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube242.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube244.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube246.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube247.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube248.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube250.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube252.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube253.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube254.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube255.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube256.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube257.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube258.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube259.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube260.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube261.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube262.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube264.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube266.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube268.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube269.geometry}
        material={materials['Material.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube270.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube272.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube274.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube275.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube276.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube277.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube278.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube279.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube280.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube281.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube282.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube283.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube284.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube285.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube287.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube289.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube291.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube292.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube293.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube295.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube297.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube298.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube299.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube300.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube301.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube302.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube303.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube304.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube305.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube306.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube307.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube308.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube309.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube311.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube313.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube315.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube316.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube317.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube319.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube321.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube322.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube323.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube324.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube325.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube326.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube327.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube328.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube329.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube330.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube331.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube332.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube333.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube334.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube335.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube336.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube337.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube338.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube339.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube340.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube341.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube342.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube343.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube344.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube345.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube346.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube347.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube348.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube349.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube350.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube351.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube352.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube353.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube354.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube355.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube356.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube357.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube358.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube359.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube360.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube361.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube362.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube363.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube364.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube365.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube366.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube367.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube368.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube369.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube370.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube371.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube372.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube373.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube374.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube375.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube376.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube377.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube378.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube379.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube380.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube381.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube382.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube383.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube384.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube385.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube386.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube387.geometry}
        material={materials['DefaultMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube388.geometry}
        material={materials['DefaultMaterial.002']}
      />
    </group>
  )
})

useGLTF.preload('/assets/heroSatellite.glb')